export const INCREMENT = 'INCREMENT'
export const ASYNC_INCREMENT = 'ASYNC_INCREMENT'
export const ASYNC_INCREMENT_START = 'ASYNC_INCREMENT_START'
export const ASYNC_INCREMENT_END = 'ASYNC_INCREMENT_END'
